FROM postgres:18.0-alpine3.22

COPY ./certs/server.crt /var/lib/postgresql/server.crt
COPY ./certs/server.key /var/lib/postgresql/server.key

RUN chown 70:70 /var/lib/postgresql/server.crt /var/lib/postgresql/server.key && \
    chmod 600 /var/lib/postgresql/server.key